//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Report.GSMServiceAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.wso2.org/php", ConfigurationName="GSMServiceAPI.GSMServicePortType")]
    public interface GSMServicePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.wso2.org/php/xsd) of message GetPriceRequest does not match the default value (http://www.wso2.org/php)
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/GetPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMS_Report.GSMServiceAPI.GetPriceResponse GetPrice(SMS_Report.GSMServiceAPI.GetPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/GetPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.GetPriceResponse> GetPriceAsync(SMS_Report.GSMServiceAPI.GetPriceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.wso2.org/php/xsd) of message GetStatusRequest does not match the default value (http://www.wso2.org/php)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.gsmservice.pl/soap/v2/gateway.php/GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMS_Report.GSMServiceAPI.GetStatusResponse GetStatus(SMS_Report.GSMServiceAPI.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.gsmservice.pl/soap/v2/gateway.php/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.GetStatusResponse> GetStatusAsync(SMS_Report.GSMServiceAPI.GetStatusRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.wso2.org/php/xsd) of message GetBalanceRequest does not match the default value (http://www.wso2.org/php)
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/GetBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMS_Report.GSMServiceAPI.GetBalanceResponse GetBalance(SMS_Report.GSMServiceAPI.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.GetBalanceResponse> GetBalanceAsync(SMS_Report.GSMServiceAPI.GetBalanceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.wso2.org/php/xsd) of message CancelRequest does not match the default value (http://www.wso2.org/php)
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/Cancel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMS_Report.GSMServiceAPI.CancelResponse Cancel(SMS_Report.GSMServiceAPI.CancelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/Cancel", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.CancelResponse> CancelAsync(SMS_Report.GSMServiceAPI.CancelRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.wso2.org/php/xsd) of message SendSMSRequest does not match the default value (http://www.wso2.org/php)
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMS_Report.GSMServiceAPI.SendSMSResponse SendSMS(SMS_Report.GSMServiceAPI.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.gsmservice.pl:443/soap/v2/gateway.php/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.SendSMSResponse> SendSMSAsync(SMS_Report.GSMServiceAPI.SendSMSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class Account : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
                this.RaisePropertyChanged("pass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class SendSMSReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errCodeField;
        
        private string descriptionField;
        
        private string recipientField;
        
        private System.Nullable<int> msgIdField;
        
        private System.Nullable<int> partsField;
        
        private System.Nullable<double> priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> msgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("msgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<double> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class CancelReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errCodeField;
        
        private string descriptionField;
        
        private System.Nullable<int> msgIdField;
        
        private string recipientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> msgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("msgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class GetBalanceReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errCodeField;
        
        private string descriptionField;
        
        private System.Nullable<double> balanceField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<double> balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class GetStatusReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errCodeField;
        
        private string descriptionField;
        
        private System.Nullable<int> msgIdField;
        
        private string recipientField;
        
        private string origDateField;
        
        private string doneDateField;
        
        private string msgStatusCodeField;
        
        private string msgStatusDescriptionField;
        
        private System.Nullable<int> msgTypeField;
        
        private System.Nullable<int> partsField;
        
        private System.Nullable<double> priceField;
        
        private string extIdField;
        
        private System.Nullable<bool> unicodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> msgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("msgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string origDate {
            get {
                return this.origDateField;
            }
            set {
                this.origDateField = value;
                this.RaisePropertyChanged("origDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string doneDate {
            get {
                return this.doneDateField;
            }
            set {
                this.doneDateField = value;
                this.RaisePropertyChanged("doneDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string msgStatusCode {
            get {
                return this.msgStatusCodeField;
            }
            set {
                this.msgStatusCodeField = value;
                this.RaisePropertyChanged("msgStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string msgStatusDescription {
            get {
                return this.msgStatusDescriptionField;
            }
            set {
                this.msgStatusDescriptionField = value;
                this.RaisePropertyChanged("msgStatusDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("msgType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<double> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string extId {
            get {
                return this.extIdField;
            }
            set {
                this.extIdField = value;
                this.RaisePropertyChanged("extId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<bool> unicode {
            get {
                return this.unicodeField;
            }
            set {
                this.unicodeField = value;
                this.RaisePropertyChanged("unicode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class GetPriceReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errCodeField;
        
        private string descriptionField;
        
        private string recipientField;
        
        private System.Nullable<int> partsField;
        
        private System.Nullable<double> priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<double> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wso2.org/php/xsd")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] recipientsField;
        
        private string messageField;
        
        private string urlField;
        
        private string udhField;
        
        private string senderField;
        
        private System.Nullable<int> msgTypeField;
        
        private System.Nullable<bool> unicodeField;
        
        private System.Nullable<int> timestampField;
        
        private System.Nullable<bool> sandboxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipients", Order=0)]
        public string[] recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
                this.RaisePropertyChanged("recipients");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string udh {
            get {
                return this.udhField;
            }
            set {
                this.udhField = value;
                this.RaisePropertyChanged("udh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("msgType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> unicode {
            get {
                return this.unicodeField;
            }
            set {
                this.unicodeField = value;
                this.RaisePropertyChanged("unicode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> sandbox {
            get {
                return this.sandboxField;
            }
            set {
                this.sandboxField = value;
                this.RaisePropertyChanged("sandbox");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPrice", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public SMS_Report.GSMServiceAPI.Account account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("messages")]
        public SMS_Report.GSMServiceAPI.Message[] messages;
        
        public GetPriceRequest() {
        }
        
        public GetPriceRequest(SMS_Report.GSMServiceAPI.Account account, SMS_Report.GSMServiceAPI.Message[] messages) {
            this.account = account;
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPriceResponse", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return")]
        public SMS_Report.GSMServiceAPI.GetPriceReturn[] @return;
        
        public GetPriceResponse() {
        }
        
        public GetPriceResponse(SMS_Report.GSMServiceAPI.GetPriceReturn[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatus", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public SMS_Report.GSMServiceAPI.Account account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("ids")]
        public string[] ids;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(SMS_Report.GSMServiceAPI.Account account, string[] ids) {
            this.account = account;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusResponse", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return")]
        public SMS_Report.GSMServiceAPI.GetStatusReturn[] @return;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(SMS_Report.GSMServiceAPI.GetStatusReturn[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalance", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public SMS_Report.GSMServiceAPI.Account account;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(SMS_Report.GSMServiceAPI.Account account) {
            this.account = account;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBalanceResponse", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public SMS_Report.GSMServiceAPI.GetBalanceReturn @return;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(SMS_Report.GSMServiceAPI.GetBalanceReturn @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Cancel", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class CancelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public SMS_Report.GSMServiceAPI.Account account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("ids")]
        public string[] ids;
        
        public CancelRequest() {
        }
        
        public CancelRequest(SMS_Report.GSMServiceAPI.Account account, string[] ids) {
            this.account = account;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelResponse", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class CancelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return")]
        public SMS_Report.GSMServiceAPI.CancelReturn[] @return;
        
        public CancelResponse() {
        }
        
        public CancelResponse(SMS_Report.GSMServiceAPI.CancelReturn[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        public SMS_Report.GSMServiceAPI.Account account;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("messages")]
        public SMS_Report.GSMServiceAPI.Message[] messages;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(SMS_Report.GSMServiceAPI.Account account, SMS_Report.GSMServiceAPI.Message[] messages) {
            this.account = account;
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="http://www.wso2.org/php/xsd", IsWrapped=true)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.wso2.org/php/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return")]
        public SMS_Report.GSMServiceAPI.SendSMSReturn[] @return;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(SMS_Report.GSMServiceAPI.SendSMSReturn[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GSMServicePortTypeChannel : SMS_Report.GSMServiceAPI.GSMServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GSMServicePortTypeClient : System.ServiceModel.ClientBase<SMS_Report.GSMServiceAPI.GSMServicePortType>, SMS_Report.GSMServiceAPI.GSMServicePortType {
        
        public GSMServicePortTypeClient() {
        }
        
        public GSMServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GSMServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GSMServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GSMServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS_Report.GSMServiceAPI.GetPriceResponse SMS_Report.GSMServiceAPI.GSMServicePortType.GetPrice(SMS_Report.GSMServiceAPI.GetPriceRequest request) {
            return base.Channel.GetPrice(request);
        }
        
        public SMS_Report.GSMServiceAPI.GetPriceReturn[] GetPrice(SMS_Report.GSMServiceAPI.Account account, SMS_Report.GSMServiceAPI.Message[] messages) {
            SMS_Report.GSMServiceAPI.GetPriceRequest inValue = new SMS_Report.GSMServiceAPI.GetPriceRequest();
            inValue.account = account;
            inValue.messages = messages;
            SMS_Report.GSMServiceAPI.GetPriceResponse retVal = ((SMS_Report.GSMServiceAPI.GSMServicePortType)(this)).GetPrice(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.GetPriceResponse> SMS_Report.GSMServiceAPI.GSMServicePortType.GetPriceAsync(SMS_Report.GSMServiceAPI.GetPriceRequest request) {
            return base.Channel.GetPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.GetPriceResponse> GetPriceAsync(SMS_Report.GSMServiceAPI.Account account, SMS_Report.GSMServiceAPI.Message[] messages) {
            SMS_Report.GSMServiceAPI.GetPriceRequest inValue = new SMS_Report.GSMServiceAPI.GetPriceRequest();
            inValue.account = account;
            inValue.messages = messages;
            return ((SMS_Report.GSMServiceAPI.GSMServicePortType)(this)).GetPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS_Report.GSMServiceAPI.GetStatusResponse SMS_Report.GSMServiceAPI.GSMServicePortType.GetStatus(SMS_Report.GSMServiceAPI.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public SMS_Report.GSMServiceAPI.GetStatusReturn[] GetStatus(SMS_Report.GSMServiceAPI.Account account, string[] ids) {
            SMS_Report.GSMServiceAPI.GetStatusRequest inValue = new SMS_Report.GSMServiceAPI.GetStatusRequest();
            inValue.account = account;
            inValue.ids = ids;
            SMS_Report.GSMServiceAPI.GetStatusResponse retVal = ((SMS_Report.GSMServiceAPI.GSMServicePortType)(this)).GetStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.GetStatusResponse> SMS_Report.GSMServiceAPI.GSMServicePortType.GetStatusAsync(SMS_Report.GSMServiceAPI.GetStatusRequest request) {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.GetStatusResponse> GetStatusAsync(SMS_Report.GSMServiceAPI.Account account, string[] ids) {
            SMS_Report.GSMServiceAPI.GetStatusRequest inValue = new SMS_Report.GSMServiceAPI.GetStatusRequest();
            inValue.account = account;
            inValue.ids = ids;
            return ((SMS_Report.GSMServiceAPI.GSMServicePortType)(this)).GetStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS_Report.GSMServiceAPI.GetBalanceResponse SMS_Report.GSMServiceAPI.GSMServicePortType.GetBalance(SMS_Report.GSMServiceAPI.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public SMS_Report.GSMServiceAPI.GetBalanceReturn GetBalance(SMS_Report.GSMServiceAPI.Account account) {
            SMS_Report.GSMServiceAPI.GetBalanceRequest inValue = new SMS_Report.GSMServiceAPI.GetBalanceRequest();
            inValue.account = account;
            SMS_Report.GSMServiceAPI.GetBalanceResponse retVal = ((SMS_Report.GSMServiceAPI.GSMServicePortType)(this)).GetBalance(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.GetBalanceResponse> SMS_Report.GSMServiceAPI.GSMServicePortType.GetBalanceAsync(SMS_Report.GSMServiceAPI.GetBalanceRequest request) {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.GetBalanceResponse> GetBalanceAsync(SMS_Report.GSMServiceAPI.Account account) {
            SMS_Report.GSMServiceAPI.GetBalanceRequest inValue = new SMS_Report.GSMServiceAPI.GetBalanceRequest();
            inValue.account = account;
            return ((SMS_Report.GSMServiceAPI.GSMServicePortType)(this)).GetBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS_Report.GSMServiceAPI.CancelResponse SMS_Report.GSMServiceAPI.GSMServicePortType.Cancel(SMS_Report.GSMServiceAPI.CancelRequest request) {
            return base.Channel.Cancel(request);
        }
        
        public SMS_Report.GSMServiceAPI.CancelReturn[] Cancel(SMS_Report.GSMServiceAPI.Account account, string[] ids) {
            SMS_Report.GSMServiceAPI.CancelRequest inValue = new SMS_Report.GSMServiceAPI.CancelRequest();
            inValue.account = account;
            inValue.ids = ids;
            SMS_Report.GSMServiceAPI.CancelResponse retVal = ((SMS_Report.GSMServiceAPI.GSMServicePortType)(this)).Cancel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.CancelResponse> SMS_Report.GSMServiceAPI.GSMServicePortType.CancelAsync(SMS_Report.GSMServiceAPI.CancelRequest request) {
            return base.Channel.CancelAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.CancelResponse> CancelAsync(SMS_Report.GSMServiceAPI.Account account, string[] ids) {
            SMS_Report.GSMServiceAPI.CancelRequest inValue = new SMS_Report.GSMServiceAPI.CancelRequest();
            inValue.account = account;
            inValue.ids = ids;
            return ((SMS_Report.GSMServiceAPI.GSMServicePortType)(this)).CancelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS_Report.GSMServiceAPI.SendSMSResponse SMS_Report.GSMServiceAPI.GSMServicePortType.SendSMS(SMS_Report.GSMServiceAPI.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public SMS_Report.GSMServiceAPI.SendSMSReturn[] SendSMS(SMS_Report.GSMServiceAPI.Account account, SMS_Report.GSMServiceAPI.Message[] messages) {
            SMS_Report.GSMServiceAPI.SendSMSRequest inValue = new SMS_Report.GSMServiceAPI.SendSMSRequest();
            inValue.account = account;
            inValue.messages = messages;
            SMS_Report.GSMServiceAPI.SendSMSResponse retVal = ((SMS_Report.GSMServiceAPI.GSMServicePortType)(this)).SendSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.SendSMSResponse> SMS_Report.GSMServiceAPI.GSMServicePortType.SendSMSAsync(SMS_Report.GSMServiceAPI.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS_Report.GSMServiceAPI.SendSMSResponse> SendSMSAsync(SMS_Report.GSMServiceAPI.Account account, SMS_Report.GSMServiceAPI.Message[] messages) {
            SMS_Report.GSMServiceAPI.SendSMSRequest inValue = new SMS_Report.GSMServiceAPI.SendSMSRequest();
            inValue.account = account;
            inValue.messages = messages;
            return ((SMS_Report.GSMServiceAPI.GSMServicePortType)(this)).SendSMSAsync(inValue);
        }
    }
}
